apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-cm
  labels:
    app: {{ .Chart.Name }}
data:
{{- range $key, $value := .Values.configMap.data }}
  {{ $key }}: {{ $value | quote }}
{{- end }}