apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-sv
  labels:
    app: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
   - port: {{ .Values.service.port }}
  selector:
   app: {{ .Values.storage.capacity }}