apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRESQL_USER: admin
  POSTGRESQL_PASSWORD: admin123$
  POSTGRESQL_DATABASE: admindb
  POSTGRESQL_ADMIN_PASSWORD: Admin123$